config/routes.rb
Fitztwit::Application.routes.draw do

  root :to => "console#index"

  get "home/index"
  get "login", :controller => 'home', :action => 'login', :as => 'login'

  get  "console/index"

  get  "console/update_approved"
  get  "console/update_pendings"
  get  "console/update_timeline"

  get  '/toggle_theme' , :controller => 'application', :action => 'toggle_theme'

  resources :messages, :only => [:index, :create, :update, :destroy] do
    member do
      put  'start_editing'
      put  'end_editing'
      put  'approve'
    end
    collection do
      post 'create_retweet_from/:status_id', :action => 'create_retweet_from', :as => :create_retweet_from
    end
  end

  get  "console/sprite"

  post "console/inject_fake_messages"
  post "console/pull_timeline"
  post "console/tweet_all_approved"
  post "console/import_timeline_changes"

end

app/views/statuses/_status.html.haml
- st = status
- from_us = st.screen_name == APP_CONFIG['twitter_account']['screen_name']
- from_friend = !from_us
- css_class = from_us ? 'from_us' : 'others'

%div.tweet(data-status-id='#{st.status_id}' data-screen-name='#{st.screen_name}'){:class => css_class}
  .hat
    %p.origin
      @#{st.screen_name}
      %span.age
        =time_ago_in_words(st.status_created_at) + ' ago'

  .box
    - if from_us
      %p.text
        = st.content

    - else
      %span.avatar
        = image_tag st.profile_image_url #, :width => '48px', :height => '48px'
      %p.text
        = st.content

  .shoes
    - if from_us
      &nbsp;
    - if from_friend
      %a.tw_sprite(onclick="init_reply_to(this)")
        %i.retweet-icon
        Reply

      - text = '<i class="retweet-icon"></i>Retweet'.html_safe
      = link_to text, create_retweet_from_messages_path(:status_id => st.status_id), :remote => true, :method => :post, :class => 'tw_sprite'